[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 src.main:server"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
# 生产环境标识
ENVIRONMENT = "production"
# 禁用调试模式
DEBUG = "false"
# 设置时区
TZ = "Asia/Shanghai"